#!/usr/bin/env python3
"""Build the public 60-paper metadata corpus from reviewed records."""

from __future__ import annotations

import json
from pathlib import Path


# venue, year, field, title, official_url, pdf_url, style, figure, page, visual note
ROWS = [
    ("CVPR", 2024, "vision", "CoDe: An Explicit Content Decoupling Framework for Image Restoration", "https://doi.org/10.1109/CVPR52733.2024.00282", "https://openaccess.thecvf.com/content/CVPR2024/papers/Gu_CoDe_An_Explicit_Content_Decoupling_Framework_for_Image_Restoration_CVPR_2024_paper.pdf", "visual-semantic", "Fig. 2", 3, "Paired image examples flank a compact content/style decomposition pipeline."),
    ("CVPR", 2024, "vision", "MedM2G: Unifying Medical Multi-Modal Generation via Cross-Guided Diffusion with Visual Invariant", "https://doi.org/10.1109/CVPR52733.2024.01093", "https://openaccess.thecvf.com/content/CVPR2024/papers/Zhan_MedM2G_Unifying_Medical_Multi-Modal_Generation_via_Cross-Guided_Diffusion_with_Visual_CVPR_2024_paper.pdf", "structured-pipeline", "Fig. 2", 3, "Modality lanes and diffusion losses are separated with repeated color coding."),
    ("CVPR", 2024, "vision", "Instruct 4D-to-4D: Editing 4D Scenes as Pseudo-3D Scenes Using 2D Diffusion", "https://doi.org/10.1109/CVPR52733.2024.01907", "https://openaccess.thecvf.com/content/CVPR2024/papers/Mou_Instruct_4D-to-4D_Editing_4D_Scenes_as_Pseudo-3D_Scenes_Using_2D_Diffusion_CVPR_2024_paper.pdf", "visual-semantic", "Fig. 2", 3, "Rendered scene states and vector modules alternate along a temporal editing flow."),
    ("CVPR", 2024, "vision", "Contrastive Pre-Training with Multi-View Fusion for No-Reference Point Cloud Quality Assessment", "https://doi.org/10.1109/CVPR52733.2024.02451", "https://openaccess.thecvf.com/content/CVPR2024/papers/Shan_Contrastive_Pre-Training_with_Multi-View_Fusion_for_No-Reference_Point_Cloud_Quality_CVPR_2024_paper.pdf", "structured-pipeline", "Fig. 2", 4, "Multi-view branches converge into fusion and contrastive objectives."),

    ("CVPR", 2025, "vision", "Functionality Understanding and Segmentation in 3D Scenes", "https://openaccess.thecvf.com/content/CVPR2025/html/Corsetti_Functionality_Understanding_and_Segmentation_in_3D_Scenes_CVPR_2025_paper.html", "https://openaccess.thecvf.com/content/CVPR2025/papers/Corsetti_Functionality_Understanding_and_Segmentation_in_3D_Scenes_CVPR_2025_paper.pdf", "visual-semantic", "Fig. 2", 3, "3D scene inputs and semantic regions carry most of the explanation."),
    ("CVPR", 2025, "vision", "Align3R: Aligned Monocular Depth Estimation for Dynamic Videos", "https://openaccess.thecvf.com/content/CVPR2025/html/Lu_Align3R_Aligned_Monocular_Depth_Estimation_for_Dynamic_Videos_CVPR_2025_paper.html", "https://openaccess.thecvf.com/content/CVPR2025/papers/Lu_Align3R_Aligned_Monocular_Depth_Estimation_for_Dynamic_Videos_CVPR_2025_paper.pdf", "visual-semantic", "Fig. 2", 3, "Video frames, depth maps, and aligned geometry form a visually led pipeline."),
    ("CVPR", 2025, "vision", "QuartDepth: Post-Training Quantization for Real-Time Depth Estimation on the Edge", "https://openaccess.thecvf.com/content/CVPR2025/html/Shen_QuartDepth_Post-Training_Quantization_for_Real-Time_Depth_Estimation_on_the_Edge_CVPR_2025_paper.html", "https://openaccess.thecvf.com/content/CVPR2025/papers/Shen_QuartDepth_Post-Training_Quantization_for_Real-Time_Depth_Estimation_on_the_Edge_CVPR_2025_paper.pdf", "minimal-modular", "Fig. 2", 3, "A small sequence of quantization modules emphasizes the intervention points."),
    ("CVPR", 2025, "vision", "Repurposing Pre-trained Video Diffusion Models for Event-based Video Interpolation", "https://openaccess.thecvf.com/content/CVPR2025/html/Chen_Repurposing_Pre-trained_Video_Diffusion_Models_for_Event-based_Video_Interpolation_CVPR_2025_paper.html", "https://openaccess.thecvf.com/content/CVPR2025/papers/Chen_Repurposing_Pre-trained_Video_Diffusion_Models_for_Event-based_Video_Interpolation_CVPR_2025_paper.pdf", "visual-semantic", "Fig. 2", 3, "Event streams and video frames are retained as thumbnail sequences around a diffusion core."),

    ("CVPR", 2026, "vision", "Spk2VidNet: A Hierarchical Recurrent Architecture for High-Fidelity Video Reconstruction from Long Spike-Camera Streams", "https://openaccess.thecvf.com/content/CVPR2026/html/Wang_Spk2VidNet_A_Hierarchical_Recurrent_Architecture_for_High-Fidelity_Video_Reconstruction_from_CVPR_2026_paper.html", "https://openaccess.thecvf.com/content/CVPR2026/papers/Wang_Spk2VidNet_A_Hierarchical_Recurrent_Architecture_for_High-Fidelity_Video_Reconstruction_from_CVPR_2026_paper.pdf", "structured-pipeline", "Fig. 2", 3, "Hierarchical recurrent stages use dense arrows while keeping a stable left-to-right baseline."),
    ("CVPR", 2026, "vision", "HybridDriveVLA: Vision-Language-Action Model with Visual CoT Reasoning and ToT Evaluation for Autonomous Driving", "https://openaccess.thecvf.com/content/CVPR2026/html/Bassole_HybridDriveVLA_Vision-Language-Action_Model_with_Visual_CoT_reasoning_and_ToT_Evaluation_CVPR_2026_paper.html", "https://openaccess.thecvf.com/content/CVPR2026/papers/Bassole_HybridDriveVLA_Vision-Language-Action_Model_with_Visual_CoT_reasoning_and_ToT_Evaluation_CVPR_2026_paper.pdf", "structured-pipeline", "Fig. 2", 3, "Perception, language reasoning, and action evaluation occupy named stages."),
    ("CVPR", 2026, "vision", "CME-CAD: Heterogeneous Collaborative Multi-Expert Reinforcement Learning for CAD Code Generation", "https://openaccess.thecvf.com/content/CVPR2026/html/Niu_CME-CAD_Heterogeneous_Collaborative_Multi-Expert_Reinforcement_Learning_for_CAD_Code_Generation_CVPR_2026_paper.html", "https://openaccess.thecvf.com/content/CVPR2026/papers/Niu_CME-CAD_Heterogeneous_Collaborative_Multi-Expert_Reinforcement_Learning_for_CAD_Code_Generation_CVPR_2026_paper.pdf", "structured-pipeline", "Fig. 2", 3, "Expert branches, CAD feedback, and reinforcement signals require explicit routing."),
    ("CVPR", 2026, "vision", "SenseSearch: Empowering Vision-Language Models with High-Resolution Agentic Search-Reasoning via Reinforcement Learning", "https://openaccess.thecvf.com/content/CVPR2026/html/Chng_SenseSearch_Empowering_Vision-Language_Models_with_High-Resolution_Agentic_Search-Reasoning_via_Reinforcement_CVPR_2026_paper.html", "https://openaccess.thecvf.com/content/CVPR2026/papers/Chng_SenseSearch_Empowering_Vision-Language_Models_with_High-Resolution_Agentic_Search-Reasoning_via_Reinforcement_CVPR_2026_paper.pdf", "visual-semantic", "Fig. 2", 3, "High-resolution crops and agent actions provide the dominant semantic examples."),

    ("ICCV", 2025, "vision", "MotionStreamer: Streaming Motion Generation via Diffusion-Based Autoregressive Model in Causal Latent Space", "https://doi.org/10.1109/ICCV51701.2025.00940", "https://openaccess.thecvf.com/content/ICCV2025/papers/Xiao_MotionStreamer_Streaming_Motion_Generation_via_Diffusion-Based_Autoregressive_Model_in_Causal_Latent_ICCV_2025_paper.pdf", "structured-pipeline", "Fig. 2", 3, "Causal latent windows and autoregressive diffusion are arranged as successive stages."),
    ("ICCV", 2025, "vision", "Improving SAM for Camouflaged Object Detection via Dual Stream Adapters", "https://doi.org/10.1109/ICCV51701.2025.02034", "https://openaccess.thecvf.com/content/ICCV2025/papers/Liu_Improving_SAM_for_Camouflaged_Object_Detection_via_Dual_Stream_Adapters_ICCV_2025_paper.pdf", "structured-pipeline", "Fig. 2", 3, "Two colored streams share a foundation model and merge near the mask decoder."),
    ("ICCV", 2025, "vision", "GCRayDiffusion: Pose-Free Surface Reconstruction via Geometric Consistent Ray Diffusion", "https://doi.org/10.1109/ICCV51701.2025.02350", "https://openaccess.thecvf.com/content/ICCV2025/papers/Chen_GCRayDiffusion_Pose-Free_Surface_Reconstruction_via_Geometric_Consistent_Ray_Diffusion_ICCV_2025_paper.pdf", "visual-semantic", "Fig. 2", 3, "Camera rays, point geometry, and reconstruction outputs anchor the flow."),
    ("ICCV", 2025, "vision", "EgoAgent: A Joint Predictive Agent Model in Egocentric Worlds", "https://doi.org/10.1109/ICCV51701.2025.00655", "https://openaccess.thecvf.com/content/ICCV2025/papers/Chen_EgoAgent_A_Joint_Predictive_Agent_Model_in_Egocentric_Worlds_ICCV_2025_paper.pdf", "structured-pipeline", "Fig. 2", 3, "Observation, prediction, and policy branches are separated into aligned lanes."),

    ("ECCV", 2024, "vision", "Probabilistic Image-Driven Traffic", "https://www.ecva.net/papers/eccv_2024/papers_ECCV/html/7781_ECCV_2024_paper.php", "https://www.ecva.net/papers/eccv_2024/papers_ECCV/papers/07781.pdf", "minimal-modular", "Fig. 2", 4, "Three inputs feed a compact encoder-decoder with three output heads."),
    ("ECCV", 2024, "vision", "Adapting Fine-Grained Cross-View Localization to Areas without Fine Ground Truth", "https://www.ecva.net/papers/eccv_2024/papers_ECCV/html/4592_ECCV_2024_paper.php", "https://www.ecva.net/papers/eccv_2024/papers_ECCV/papers/04592.pdf", "structured-pipeline", "Fig. 2", 4, "Teacher, auxiliary student, filtering, and final student are color-coded by stage."),
    ("ECCV", 2024, "vision", "GraphBEV: Towards Robust BEV Feature Alignment for Multi-Modal 3D Object Detection", "https://www.ecva.net/papers/eccv_2024/papers_ECCV/html/3796_ECCV_2024_paper.php", "https://www.ecva.net/papers/eccv_2024/papers_ECCV/papers/03796.pdf", "structured-pipeline", "Fig. 2", 4, "Camera and LiDAR encoders form parallel lanes with local/global alignment modules."),
    ("ECCV", 2024, "vision", "X-Former: Unifying Contrastive and Reconstruction Learning for MLLMs", "https://www.ecva.net/papers/eccv_2024/papers_ECCV/html/935_ECCV_2024_paper.php", "https://www.ecva.net/papers/eccv_2024/papers_ECCV/papers/00935.pdf", "structured-pipeline", "Fig. 3", 4, "Frozen encoders and multiple objectives are distinguished with branch and status encodings."),

    ("ICLR", 2024, "machine-learning", "HIFA: High-fidelity Text-to-3D Generation with Advanced Diffusion Guidance", "https://proceedings.iclr.cc/paper_files/paper/2024/hash/178ae4ba29022eb7bf509c2e27bc8ab8-Abstract-Conference.html", "https://proceedings.iclr.cc/paper_files/paper/2024/file/178ae4ba29022eb7bf509c2e27bc8ab8-Paper-Conference.pdf", "visual-semantic", "Fig. 2", 3, "Text prompts, diffusion guidance, and rendered 3D views share the visual field."),
    ("ICLR", 2024, "machine-learning", "Meta-Evolve: Continuous Robot Evolution for One-to-many Policy Transfer", "https://proceedings.iclr.cc/paper_files/paper/2024/hash/61a9278dfef5f871b5e472389f8d6fa1-Abstract-Conference.html", "https://proceedings.iclr.cc/paper_files/paper/2024/file/61a9278dfef5f871b5e472389f8d6fa1-Paper-Conference.pdf", "structured-pipeline", "Fig. 2", 4, "Evolution stages and policy transfer are shown as a structured multi-stage loop."),
    ("ICLR", 2024, "machine-learning", "Encoding Unitig-level Assembly Graphs with Heterophilous Constraints for Metagenomic Contigs Binning", "https://proceedings.iclr.cc/paper_files/paper/2024/hash/b09df3a10e26204136540ca59bc5a646-Abstract-Conference.html", "https://proceedings.iclr.cc/paper_files/paper/2024/file/b09df3a10e26204136540ca59bc5a646-Paper-Conference.pdf", "structured-pipeline", "Fig. 1", 3, "Learning, matching, propagation, and refinement are explicit sequential phases."),
    ("ICLR", 2024, "machine-learning", "FLATTEN: optical FLow-guided ATTENtion for consistent text-to-video editing", "https://proceedings.iclr.cc/paper_files/paper/2024/hash/e50dcf35e1d780cd87fed4a6f1edf293-Abstract-Conference.html", "https://proceedings.iclr.cc/paper_files/paper/2024/file/e50dcf35e1d780cd87fed4a6f1edf293-Paper-Conference.pdf", "visual-semantic", "Fig. 2", 4, "Frame thumbnails and attention/flow maps dominate the editing explanation."),

    ("ICLR", 2025, "machine-learning", "Better than Your Teacher: LLM Agents that learn from Privileged AI Feedback", "https://proceedings.iclr.cc/paper_files/paper/2025/hash/1c60ed2b01120d383eebf12dc7a0e138-Abstract-Conference.html", "https://proceedings.iclr.cc/paper_files/paper/2025/file/1c60ed2b01120d383eebf12dc7a0e138-Paper-Conference.pdf", "structured-pipeline", "Fig. 2", 3, "Agent interaction, privileged feedback, and policy updates form a training loop."),
    ("ICLR", 2025, "machine-learning", "VEDIT: Latent Prediction Architecture For Procedural Video Representation Learning", "https://proceedings.iclr.cc/paper_files/paper/2025/hash/661caac7729aa7d8c6b8ac0d39ccbc6a-Abstract-Conference.html", "https://proceedings.iclr.cc/paper_files/paper/2025/file/661caac7729aa7d8c6b8ac0d39ccbc6a-Paper-Conference.pdf", "visual-semantic", "Fig. 2", 3, "Video snippets, latent predictions, and temporal blocks alternate in the main flow."),
    ("ICLR", 2025, "machine-learning", "3D-AffordanceLLM: Harnessing Large Language Models for Open-Vocabulary Affordance Detection in 3D Worlds", "https://proceedings.iclr.cc/paper_files/paper/2025/hash/b364c8cbb3f229f40d5873e877391bd2-Abstract-Conference.html", "https://proceedings.iclr.cc/paper_files/paper/2025/file/b364c8cbb3f229f40d5873e877391bd2-Paper-Conference.pdf", "visual-semantic", "Fig. 2", 3, "3D inputs and affordance masks are integrated with language modules."),
    ("ICLR", 2025, "machine-learning", "Eagle: Exploring The Design Space for Multimodal LLMs with Mixture of Encoders", "https://proceedings.iclr.cc/paper_files/paper/2025/hash/e78457d4a04b8565f1fe5077df13cddb-Abstract-Conference.html", "https://proceedings.iclr.cc/paper_files/paper/2025/file/e78457d4a04b8565f1fe5077df13cddb-Paper-Conference.pdf", "structured-pipeline", "Fig. 2", 4, "Multiple encoder experts converge into a common language-model interface."),

    ("ICLR", 2026, "machine-learning", "Patch-as-Decodable-Token: Towards Unified Multi-Modal Vision Tasks in MLLMs", "https://openreview.net/forum?id=xF0Dcmvsl0", "https://openreview.net/pdf?id=xF0Dcmvsl0", "structured-pipeline", "Fig. 2", 3, "Visual reference tokens connect a shared MLLM to multiple task decoders."),
    ("ICLR", 2026, "machine-learning", "InSight-o3: Empowering Multimodal Foundation Models with Generalized Visual Search", "https://openreview.net/forum?id=vlraTIgUD3", "https://openreview.net/pdf?id=vlraTIgUD3", "structured-pipeline", "Fig. 2", 3, "A visual reasoner and search agent exchange crops in a clearly staged agent loop."),
    ("ICLR", 2026, "machine-learning", "Shuffle-R1: Efficient RL framework for Multimodal Large Language Models via Data-centric Dynamic Shuffle", "https://openreview.net/forum?id=mYP33u1QBK", "https://openreview.net/pdf?id=mYP33u1QBK", "structured-pipeline", "Fig. 2", 2, "Static and dynamic sampling pipelines are compared with explicit training signals."),
    ("ICLR", 2026, "machine-learning", "ThinkOmni: Lifting Textual Reasoning to Omni-modal Scenarios via Guidance Decoding", "https://openreview.net/forum?id=pMpCOjzwI1", "https://openreview.net/pdf?id=pMpCOjzwI1", "minimal-modular", "Fig. 2", 3, "A guide model and omni-modal model form a compact two-model decoding pathway."),

    ("ICML", 2025, "machine-learning", "ELEMENTAL: Interactive Learning from Demonstrations and Vision-Language Models for Reward Design in Robotics", "https://proceedings.mlr.press/v267/chen25at.html", "https://raw.githubusercontent.com/mlresearch/v267/main/assets/chen25at/chen25at.pdf", "visual-semantic", "Fig. 2", 3, "Demonstrations, language feedback, and robot rollouts are shown with real task examples."),
    ("ICML", 2025, "machine-learning", "M3-JEPA: Multimodal Alignment via Multi-gate MoE based on the Joint-Embedding Predictive Architecture", "https://proceedings.mlr.press/v267/lei25b.html", "https://raw.githubusercontent.com/mlresearch/v267/main/assets/lei25b/lei25b.pdf", "structured-pipeline", "Fig. 2", 3, "Modality-specific gates and experts converge into a predictive embedding objective."),
    ("ICML", 2025, "machine-learning", "Cradle: Empowering Foundation Agents towards General Computer Control", "https://proceedings.mlr.press/v267/tan25h.html", "https://raw.githubusercontent.com/mlresearch/v267/main/assets/tan25h/tan25h.pdf", "structured-pipeline", "Fig. 2", 3, "Perception, planning, action, and memory are arranged as a recurrent agent system."),
    ("ICML", 2025, "machine-learning", "Primitive Vision: Improving Diagram Understanding in MLLMs", "https://proceedings.mlr.press/v267/zhang25n.html", "https://raw.githubusercontent.com/mlresearch/v267/main/assets/zhang25n/zhang25n.pdf", "visual-semantic", "Fig. 2", 3, "Diagram primitives and language tokens are visibly paired before reasoning."),

    ("NeurIPS", 2025, "machine-learning", "SceneForge: Enhancing 3D-text alignment with Structured Scene Compositions", "http://papers.nips.cc/paper_files/paper/2025/hash/7a46d62a1cf6406a68b42a46e85ea28c-Abstract-Conference.html", "http://papers.nips.cc/paper_files/paper/2025/file/7a46d62a1cf6406a68b42a46e85ea28c-Paper-Conference.pdf", "visual-semantic", "Fig. 2", 3, "Structured 3D compositions and text descriptions are linked by semantic alignment modules."),
    ("NeurIPS", 2025, "machine-learning", "Transformers for Mixed-type Event Sequences", "http://papers.nips.cc/paper_files/paper/2025/hash/a6c7515ac435277dc92b75a07bb2257c-Abstract-Conference.html", "http://papers.nips.cc/paper_files/paper/2025/file/a6c7515ac435277dc92b75a07bb2257c-Paper-Conference.pdf", "minimal-modular", "Fig. 2", 3, "Typed events enter a compact transformer encoder and prediction head."),
    ("NeurIPS", 2025, "machine-learning", "HiFlow: Training-free High-Resolution Image Generation with Flow-Aligned Guidance", "http://papers.nips.cc/paper_files/paper/2025/hash/d4ecde5d18d36150c529d1b9c5f0d727-Abstract-Conference.html", "http://papers.nips.cc/paper_files/paper/2025/file/d4ecde5d18d36150c529d1b9c5f0d727-Paper-Conference.pdf", "visual-semantic", "Fig. 2", 3, "Low/high-resolution generation states and guidance paths are visually paired."),
    ("NeurIPS", 2025, "machine-learning", "The Lighthouse of Language: Enhancing LLM Agents via Critique-Guided Improvement", "http://papers.nips.cc/paper_files/paper/2025/hash/f09e8dd9274cb7c2dd0dc65ffc6f427a-Abstract-Conference.html", "http://papers.nips.cc/paper_files/paper/2025/file/f09e8dd9274cb7c2dd0dc65ffc6f427a-Paper-Conference.pdf", "structured-pipeline", "Fig. 2", 3, "Agent generation and critique are encoded as a multi-round feedback loop."),

    ("ACL", 2025, "language-multimodal-computing", "Context-Aware Sentiment Forecasting via LLM-based Multi-Perspective Role-Playing Agents", "https://aclanthology.org/2025.acl-long.136/", "https://aclanthology.org/2025.acl-long.136.pdf", "structured-pipeline", "Fig. 2", 4, "Role agents occupy distinct lanes before context aggregation and forecasting."),
    ("ACL", 2025, "language-multimodal-computing", "Knowledge-Augmented Multimodal Clinical Rationale Generation for Disease Diagnosis with Small Language Models", "https://aclanthology.org/2025.acl-long.540/", "https://aclanthology.org/2025.acl-long.540.pdf", "visual-semantic", "Fig. 2", 3, "Clinical image/text evidence and knowledge retrieval surround a small language model."),
    ("ACL", 2025, "language-multimodal-computing", "DIVE into MoE: Diversity-Enhanced Reconstruction of Large Language Models from Dense into Mixture-of-Experts", "https://aclanthology.org/2025.acl-long.951/", "https://aclanthology.org/2025.acl-long.951.pdf", "structured-pipeline", "Fig. 2", 3, "Dense-to-expert reconstruction and diversity objectives form a multi-loss pipeline."),
    ("ACL", 2025, "language-multimodal-computing", "GeLLM³O: Generalizing Large Language Models for Multi-property Molecule Optimization", "https://aclanthology.org/2025.acl-long.1225/", "https://aclanthology.org/2025.acl-long.1225.pdf", "structured-pipeline", "Fig. 2", 3, "Molecular candidates and property feedback loop through an LLM-based optimizer."),

    ("EMNLP", 2025, "language-multimodal-computing", "Dialect-SQL: An Adaptive Framework for Bridging the Dialect Gap in Text-to-SQL", "https://aclanthology.org/2025.emnlp-main.178/", "https://aclanthology.org/2025.emnlp-main.178.pdf", "structured-pipeline", "Fig. 2", 3, "Dialect adaptation, schema context, and SQL generation are separated into stages."),
    ("EMNLP", 2025, "language-multimodal-computing", "Advancing Fine-Grained Visual Understanding with Multi-Scale Alignment in Multi-Modal Models", "https://aclanthology.org/2025.emnlp-main.721/", "https://aclanthology.org/2025.emnlp-main.721.pdf", "visual-semantic", "Fig. 2", 3, "Multi-scale image regions and language tokens are aligned in parallel."),
    ("EMNLP", 2025, "language-multimodal-computing", "RAG-Zeval: Enhancing RAG Responses Evaluator through End-to-End Reasoning and Ranking-Based Reinforcement Learning", "https://aclanthology.org/2025.emnlp-main.1267/", "https://aclanthology.org/2025.emnlp-main.1267.pdf", "structured-pipeline", "Fig. 2", 3, "Retrieval, reasoning, ranking, and reward paths require explicit training routing."),
    ("EMNLP", 2025, "language-multimodal-computing", "SQUiD: Synthesizing Relational Databases from Unstructured Text", "https://aclanthology.org/2025.emnlp-main.1629/", "https://aclanthology.org/2025.emnlp-main.1629.pdf", "structured-pipeline", "Fig. 2", 3, "Text extraction, schema induction, and relational synthesis form three clear stages."),

    ("AAAI", 2025, "language-multimodal-computing", "Auto-Regressive Diffusion for Generating 3D Human-Object Interactions", "https://doi.org/10.1609/aaai.v39i3.32322", "https://ojs.aaai.org/index.php/AAAI/article/download/32322/34477", "visual-semantic", "Fig. 2", 3, "Human/object geometry and autoregressive denoising states lead the visual narrative."),
    ("AAAI", 2025, "language-multimodal-computing", "UniFORM: Towards Unified Framework for Anomaly Detection on Graphs", "https://doi.org/10.1609/aaai.v39i12.33369", "https://ojs.aaai.org/index.php/AAAI/article/download/33369/35524", "structured-pipeline", "Fig. 2", 3, "Multiple anomaly signals share graph encoders and converge into a unified objective."),
    ("AAAI", 2025, "language-multimodal-computing", "HeterGP: Bridging Heterogeneity in Graph Neural Networks with Multi-View Prompting", "https://doi.org/10.1609/aaai.v39i20.35496", "https://ojs.aaai.org/index.php/AAAI/article/download/35496/37651", "structured-pipeline", "Fig. 2", 3, "Heterogeneous graph views and prompt branches merge into a shared GNN."),
    ("AAAI", 2025, "language-multimodal-computing", "FAP-CD: Fairness-Driven Age-Friendly Community Planning via Conditional Diffusion Generation", "https://doi.org/10.1609/aaai.v39i27.35036", "https://ojs.aaai.org/index.php/AAAI/article/download/35036/37191", "visual-semantic", "Fig. 2", 3, "Community layouts and fairness conditions are shown beside the diffusion process."),

    ("ACM MM", 2025, "language-multimodal-computing", "Art4Math: Handwritten Mathematical Expression Recognition via Multimodal Sketch Grounding", "https://doi.org/10.1145/3746027.3755247", "https://dl.acm.org/doi/pdf/10.1145/3746027.3755247", "visual-semantic", "Fig. 2", 3, "Handwritten expressions, sketches, and symbolic tokens are visually aligned."),
    ("ACM MM", 2025, "language-multimodal-computing", "MIRA: A Novel Framework for Fusing Modalities in Medical RAG", "https://doi.org/10.1145/3746027.3755760", "https://dl.acm.org/doi/pdf/10.1145/3746027.3755760", "structured-pipeline", "Fig. 2", 3, "Medical image/text retrieval lanes merge before answer generation."),
    ("ACM MM", 2025, "language-multimodal-computing", "Mavors: Multi-granularity Video Representation for Multimodal Large Language Model", "https://doi.org/10.1145/3746027.3755363", "https://dl.acm.org/doi/pdf/10.1145/3746027.3755363", "visual-semantic", "Fig. 2", 3, "Video thumbnails and multi-granularity tokens are arranged as a visual hierarchy."),
    ("ACM MM", 2025, "language-multimodal-computing", "BridgeNet: A Unified Multimodal Framework for Bridging 2D and 3D Industrial Anomaly Detection", "https://doi.org/10.1145/3746027.3755261", "https://dl.acm.org/doi/pdf/10.1145/3746027.3755261", "structured-pipeline", "Fig. 2", 3, "2D and 3D branches share bridging modules and anomaly heads."),

    ("SIGGRAPH", 2025, "language-multimodal-computing", "ForceGrip: Reference-Free Curriculum Learning for Realistic Grip Force Control in VR Hand Manipulation", "https://doi.org/10.1145/3721238.3730738", "https://dl.acm.org/doi/pdf/10.1145/3721238.3730738", "visual-semantic", "Fig. 2", 3, "Hand-object interaction examples and curriculum stages share the canvas."),
    ("SIGGRAPH", 2025, "language-multimodal-computing", "Scene-Level Appearance Transfer with Semantic Correspondences", "https://doi.org/10.1145/3721238.3730655", "https://dl.acm.org/doi/pdf/10.1145/3721238.3730655", "visual-semantic", "Fig. 2", 3, "Source/target scene thumbnails and correspondence maps dominate the method figure."),
    ("SIGGRAPH", 2025, "language-multimodal-computing", "IP-Prompter: Training-Free Theme-Specific Image Generation via Dynamic Visual Prompting", "https://doi.org/10.1145/3721238.3730670", "https://dl.acm.org/doi/pdf/10.1145/3721238.3730670", "visual-semantic", "Fig. 2", 3, "Reference images, visual prompts, and generated outputs form a semantic sequence."),
    ("SIGGRAPH", 2025, "language-multimodal-computing", "DeepMill: Neural Accessibility Learning for Subtractive Manufacturing", "https://doi.org/10.1145/3721238.3730657", "https://dl.acm.org/doi/pdf/10.1145/3721238.3730657", "structured-pipeline", "Fig. 2", 3, "Geometry sampling, neural accessibility, and manufacturing decisions form structured stages."),
]


PROFILES = {
    "minimal-modular": dict(layout="left-to-right", branch_count=1, panel_count=1, real_image_ratio=0.08, color_count=2, icon_density="low", edge_routing="direct/orthogonal", training_inference_split="none", shared_parameter_encoding="single labeled module"),
    "visual-semantic": dict(layout="image-to-representation-to-output", branch_count=2, panel_count=2, real_image_ratio=0.38, color_count=3, icon_density="high", edge_routing="orthogonal near merges", training_inference_split="caption or line style", shared_parameter_encoding="shared core with modality colors"),
    "structured-pipeline": dict(layout="multi-lane left-to-right", branch_count=3, panel_count=3, real_image_ratio=0.12, color_count=4, icon_density="medium", edge_routing="orthogonal", training_inference_split="panels/dashed paths", shared_parameter_encoding="singleton with named ports"),
}


def main() -> None:
    if len(ROWS) != 60:
        raise SystemExit(f"expected 60 rows, got {len(ROWS)}")
    by_group: dict[tuple[str, int], int] = {}
    records = []
    for index, row in enumerate(ROWS, 1):
        venue, year, field, title, official, pdf, profile, figure, page, note = row
        key = (venue, year)
        slot = by_group.get(key, 0)
        by_group[key] = slot + 1
        position = [0.10, 0.40, 0.70, 0.90][slot]
        record = {
            "id": f"paper-{index:02d}", "title": title, "venue": venue, "year": year, "field": field,
            "selection_position": position, "official_url": official, "pdf_url": pdf,
            "primary_figure": figure, "figure_page": page, "style": profile,
            "typography": "conference template; figure labels predominantly sans-serif/mixed",
            **PROFILES[profile],
            "visual_observation": note,
            "inspection": {
                "abstract": True, "method_overview_paragraph": True, "main_figure": True, "caption": True,
                "basis": "official proceedings/acceptance page plus conference or author PDF",
                "checked_on": "2026-07-21"
            }
        }
        records.append(record)
    payload = {
        "schema_version": "2.0.0",
        "license_note": "Bibliographic metadata and original coded observations only; no paper figures are redistributed.",
        "sampling": "15 venue-year groups × 4 qualified main-track papers near 10/40/70/90 percent positions.",
        "papers": records,
    }
    target = Path(__file__).with_name("papers.json")
    target.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {target} ({len(records)} papers)")


if __name__ == "__main__":
    main()
